name: "Agent Runner"
description: "Run agent commands in isolated worktree"
inputs:
  command:
    description: "Command to run (start, run, finish)"
    required: true
  args:
    description: "Additional arguments (JSON array or space-separated)"
    required: false
    default: "[]"
outputs:
  agent_id:
    description: "Agent ID for subsequent commands"
    value: ${{ steps.run.outputs.agent_id }}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install agent-tools
      shell: bash
      run: |
        cd agt
        pip install -e .
    
    - name: Run agent command
      id: run
      shell: bash
      env:
        AGENT_ID: ${{ env.AGENT_ID }}
      run: |
        cd agt
        python -m agt ${{ inputs.command }} ${{ inputs.args }}

